// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_OeajEU5Ewl4NgxMgBg1SBv6eS783xf8',
    appId: '1:615602997008:web:8cef22792f992a53ca4795',
    messagingSenderId: '615602997008',
    projectId: 'studentai-dbf06',
    authDomain: 'studentai-dbf06.firebaseapp.com',
    storageBucket: 'studentai-dbf06.firebasestorage.app',
    measurementId: 'G-2XXW6VPLQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-XT_v1ceBT8pl2MHaTnTBev5LCRvOUc',
    appId: '1:615602997008:android:2425266cb3913f45ca4795',
    messagingSenderId: '615602997008',
    projectId: 'studentai-dbf06',
    storageBucket: 'studentai-dbf06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB84j6_p24iKCOu1ywFypUJfU5zz_WyKuI',
    appId: '1:565508297515:ios:332fdf56fd6b993837ab6e',
    messagingSenderId: '565508297515',
    projectId: 'mentorai-2afce',
    storageBucket: 'mentorai-2afce.firebasestorage.app',
    iosBundleId: 'com.vectorlabs.mentorai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB84j6_p24iKCOu1ywFypUJfU5zz_WyKuI',
    appId: '1:565508297515:ios:6105734f31fc3ac237ab6e',
    messagingSenderId: '565508297515',
    projectId: 'mentorai-2afce',
    storageBucket: 'mentorai-2afce.firebasestorage.app',
    iosBundleId: 'com.example.studentAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_OeajEU5Ewl4NgxMgBg1SBv6eS783xf8',
    appId: '1:615602997008:web:a55c3f84a2ed15b2ca4795',
    messagingSenderId: '615602997008',
    projectId: 'studentai-dbf06',
    authDomain: 'studentai-dbf06.firebaseapp.com',
    storageBucket: 'studentai-dbf06.firebasestorage.app',
    measurementId: 'G-RM21SYJQ6F',
  );
}